export const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
]

export const cities = [
  'Tokyo',
  'New York City',
  'London',
  'Paris',
  'Sydney',
  'Rio de Janeiro',
  'Moscow',
  'Toronto',
  'Dubai',
  'Mumbai',
  'Berlin',
  'Cape Town',
  'Singapore',
  'Mexico City',
  'Tokyo',
  'Seoul',
  'Amsterdam',
  'Rome',
  'Istanbul',
  'Bangkok',
]

export const galleryImages = [
  {
    id: 1,
    title: 'Image 1',
    url: 'https://picsum.photos/id/1/300/300',
  },
  {
    id: 2,
    title: 'Image 2',
    url: 'https://picsum.photos/id/2/300/300',
  },
  {
    id: 3,
    title: 'Image 3',
    url: 'https://picsum.photos/id/3/300/300',
  },
  {
    id: 4,
    title: 'Image 4',
    url: 'https://picsum.photos/id/4/300/300',
  },
  {
    id: 5,
    title: 'Image 5',
    url: 'https://picsum.photos/id/5/300/300',
  },
  {
    id: 6,
    title: 'Image 6',
    url: 'https://picsum.photos/id/6/300/300',
  },
]

export const HomePageBackgrounds = [
  {
    id: 1,
    title: 'your baking connection',
    subTitle: 'The online marketplace for home bakeries. We connect home bakers to local buyers.',
    url: '/Images/homepage-background.webp',
  },
  {
    id: 2,
    title: 'Bake With Passion',
    subTitle:
      'Unleash your inner pastry chef. Connect with local buyers through our online marketplace for home bakers.',
    url: 'https://assets.bonappetit.com/photos/57acad861b3340441497511a/16:9/w_2560%2Cc_limit/chocolate-or-vanilla-cream-cheese-frosting.jpg',
  },
  {
    id: 3,
    title: 'Deliciously Fresh',
    subTitle: 'From our ovens to you, savor the taste of handcrafted baked treats.',
    url: 'https://media.istockphoto.com/id/1141009146/photo/cheerful-polka-dot-cupcakes.jpg?s=612x612&w=0&k=20&c=hVnMNFiw93Dg8fBkR7GMBFgzdJyWyBymhTECvixaYw4=',
  },
  {
    id: 4,
    title: 'Taste the Difference',
    subTitle:
      'Handcrafted perfection, one bite at a time. Discover the delectable creations from our talented bakers.',
    url: 'https://w0.peakpx.com/wallpaper/477/651/HD-wallpaper-cupcakes-dessert-cream-sweet.jpg',
  },
]

export const accordionData = [
  {
    id: 0,
    title: 'Is there a free trial available?',
    content:
      'Yes, you can try us for free for 30 days. If you want, we’ll provide you with a free, personalized 30-minute onboarding call to get you up and running as soon as possible.',
  },
  {
    id: 1,
    title: 'Can I change my plan later?',
    content: `In fractional property ownership, you buy a specific quantity or fraction of a property. You can choose the amount you can afford based on the total available. The property is managed by professionals serving as trustees, and you can earn dividends(if property is on lease/let) and potentially sell a fraction or all of your units in the future. As co-owners you all have control on what happens to the property through weighted votes based on your holding.`,
  },
  {
    id: 2,
    title: 'What is your cancellation policy?',
    content: `Fractional property investing offers several benefits, including the ability to diversify your real estate portfolio by owning fractions of different properties. It allows you to invest in high-value properties that may have been otherwise unaffordable. Additionally, fractional property investing provides you liquidity, as you can sell your fractions/units when needed.
      `,
  },
  {
    id: 3,
    title: `Can other info be added to an invoice?`,
    content: `If the property is available for letting, you can earn dividends based on your holding. Dividends are distributed based on the leasing income generated by the property, allowing you to earn regular income from your investment.`,
  },
  {
    id: 4,
    title: `How does billing work?`,
    content: `On the Partown fractional property marketplace, you have the option to sell your units by just listing the quantity you want to sell at a particular price. It is advisable to sell as close as possible to the market value so you protect your returns and have a quick turnaround. You can choose to sell only the quantities that meet your immediate needs, this provides flexibility and just-in-time liquidity.`,
  },
  {
    id: 5,
    title: `How do I change my account email?`,
    content: `This is easy, you just need to add a bank account to your profile and specify the amount you intend to withdraw. We will send you a notification to verify by email or text message before wiring the proceeds to your account. The whole process takes about two(2) days.`,
  },
]

export const ReviewCardsData = [
  {
    id: 1,
    name: 'John Doe',
    image: 'https://picsum.photos/id/1/300/300',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc.',
  },
  {
    id: 2,
    name: 'Sara Austin',
    image: 'https://picsum.photos/id/2/300/300',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod,',
  },
  {
    id: 3,
    name: 'robert kent',
    image: 'https://picsum.photos/id/3/300/300',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc.',
  },
  {
    id: 4,
    name: 'Suzy Clark',
    image: 'https://picsum.photos/id/4/300/300',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc.',
  },
]

export const profileNavigation = [
  {
    id: 1,
    title: 'My Profile',
    icon: '/Images/user.svg',
  },
  {
    id: 2,
    title: 'Payment details',
    icon: '/Images/payment-details.svg',
  },
  {
    id: 3,
    title: 'purchase history',
    icon: '/Images/history.svg',
  },
  {
    id: 4,
    title: 'settings',
    icon: '/Images/setting.svg',
  },
  {
    id: 5,
    title: 'help',
    icon: '/Images/help.svg',
  },
  {
    id: 6,
    title: 'logout',
    icon: '/Images/logout.svg',
  },
]
