stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

# THIS IS THE PIPELINE FOR TEST BRANCH
build-staging: # This job runs in the build stage, which runs first.
  stage: build
  only:
    - staging
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
  script:
    - pwd
    - echo "$ENV_FILE_STAGING" > .env
#    - ls
#    - cat .env
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu && rm -rf pipeline-staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu && mkdir pipeline-staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-staging && git clone https://gitlab+deploy-token-2272113:2xea47Mx1Brp3Tz-eaw_@gitlab.com/Codistan/yourbakingconnection/user-panel.git"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-test/user-panel && git checkout staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-test/user-panel && rm -rf .env"
    - scp -r /builds/Codistan/yourbakingconnection/user-panel/.env $HOSTNAME@$PUBLIC_KEY:/home/ubuntu/pipeline-staging/user-panel
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-staging/user-panel && npm install --legacy-peer-deps"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-staging/user-panel && npm run build"


deploy-staging:
  only:
    - staging
  stage: deploy

  script:
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    #- ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-staging/user-panel && pm2 start "npm start" --name app-staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-staging/user-panel && npm start"

#build-main: # This job runs in the build stage, which runs first.
#  stage: build
#  only:
#    - main
#  before_script:
#    - apt update
#    - touch .env
#    - mkdir ~/.ssh
#    - eval $(ssh-agent -s)
#    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
#    - chmod 700 /root/.ssh
#    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
#  script:
#    - pwd
#    - echo "$ENV_FILE_STAGING" > .env
#    - ls
#    - cat .env
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu && rm -rf pipeline-main"
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu && mkdir pipeline-main"
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-main && git clone https://gitlab+deploy-token-2272113:2xea47Mx1Brp3Tz-eaw_@gitlab.com/Codistan/yourbakingconnection/user-panel.git"
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-main/user-panel && git checkout main"
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-main/user-panel && rm -rf .env"
#    - scp -r /builds/Codistan/yourbakingconnection/user-panel/.env $HOSTNAME@$PUBLIC_KEY:/home/ubuntu/pipeline-main/user-panel
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-main/user-panel && npm install --legacy-peer-deps"
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-main/user-panel && npm run build"

#deploy-main:
#  only:
#    - main
#  stage: deploy

#  script:
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/pipeline-main/user-panel && pm2 start "npm start" --name app-main"