query catalogItems($shopIds: [ID]!, $first: ConnectionLimitInt, $offset: Int) {
  catalogItems(shopIds: $shopIds, first: $first, offset: $offset) {
    totalCount
    edges {
      node {
        ... on CatalogItemProduct {
          product {
            _id
            title
            slug
            description
            media {
              URLs {
                thumbnail
              }
            }
            variants {
              variantId
              pricing {
                compareAtPrice {
                  amount
                  displayAmount
                }
                price
              }
            }
          }
        }
      }
    }
  }
}
