query baker($shopId: ID!) {
  baker(shopId: $shopId) {
    _id
    name
    slug
    description
    shopLogoUrls {
      primaryShopLogoUrl
    }
    categories {
      _id
      name
      image
    }
    featuredShopImages {
      URLs {
        large
        medium
        small
        thumbnail
      }
    }
    addressBook {
      city
      region
    }
  }
}
